server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-student
  datasource:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/springbootkeycloak
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

info:
  application:
     name: api-student
    
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

jwt:
  auth:
    converter:
      resource-id: spring-boot
      principal-attribute: preferred_username
          
logging:
  level:
    org:
      springframework:
        security: DEBUG