server:
  port: ${PORT:${SERVER_PORT:8090}}
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
spring:
  cloud:
    gateway:
      routes:
      - id: api-student
        uri: lb://api-student
        predicates:
          - Path=/api/students/**
        filters:
          - StripPrefix=2